version: '3.4'

services:
  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hacker
      MONGO_INITDB_ROOT_PASSWORD: hacking
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hacker
      ME_CONFIG_MONGODB_ADMINPASSWORD: hacking
    depends_on:
      - mongo

  mongo-seed:
    build:
      context: ./mongo-seed
      dockerfile: ./Dockerfile
      args:
        - URI=mongodb://hacker:hacking@mongo:27017/?authSource=admin
    depends_on:
      - mongo

  bank-mock-api:
    build: ./src/BankMockAPI
    restart: always
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  payment-api:
    build: ./src/PaymentAPI
    restart: always
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_CONNECTION_STRING=mongodb://hacker:hacking@mongo:27017/?authSource=admin
      - BANKING_API_BASE_ADDRESS=http://bank-mock-api
    depends_on:
      - mongo
      - bank-mock-api
        
  prometheus:
    build: ./prometheus
    ports:
        - 9090:9090
    depends_on:
      - payment-api
